import 'package:flutter/material.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          OpeningPage(),
        ]),
      ),
    );
  }
}

class OpeningPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 391,
                  height: 844,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/391x844"),
                      fit: BoxFit.cover,
                    ),                  ),
                ),
              ),
              Positioned(
                left: 66,
                top: 388,
                child: Text(
                  'CropCare',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 56,
                    fontFamily: 'Lora',
                    fontWeight: FontWeight.w700,
                    height: 0.02,
                    letterSpacing: 0.56,
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFF3F2F2)),
          child: Stack(
            children: [
              Positioned(
                left: 33,
                top: 704,
                child: Container(
                  width: 320,
                  height: 44,
                  padding: const EdgeInsets.symmetric(horizontal: 16),
                  decoration: ShapeDecoration(
                    color: Color(0xFF36946F),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Continue',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.black.withOpacity(0.800000011920929),
                          fontSize: 14,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w500,
                          height: 0.07,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 104,
                child: SizedBox(
                  width: 302,
                  child: Text(
                    'Language',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF285352),
                      fontSize: 32,
                      fontFamily: 'Lora',
                      fontWeight: FontWeight.w600,
                      height: 0.03,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 178,
                top: 764,
                child: Text(
                  'Skip',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFF285352),
                    fontSize: 15,
                    fontFamily: 'Merriweather',
                    fontWeight: FontWeight.w700,
                    decoration: TextDecoration.underline,
                    height: 0.07,
                  ),
                ),
              ),
              Positioned(
                left: 101,
                top: 162,
                child: Text(
                  'choose your language',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFF36946F),
                    fontSize: 18,
                    fontFamily: 'Lora',
                    fontWeight: FontWeight.w400,
                    height: 0.06,
                  ),
                ),
              ),
              Positioned(
                left: 113,
                top: 303,
                child: Container(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 32.74,
                              height: 32.74,
                              padding: const EdgeInsets.all(2.73),
                              decoration: ShapeDecoration(
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(4.09),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    width: 27.28,
                                    height: 27.28,
                                    padding: const EdgeInsets.all(6.82),
                                    clipBehavior: Clip.antiAlias,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(width: 2.73, color: Color(0xFF2D3648)),
                                        borderRadius: BorderRadius.circular(13640.83),
                                      ),
                                    ),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                  
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(width: 38),
                            Text(
                              'English',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFF285352),
                                fontSize: 24.56,
                                fontFamily: 'Lora',
                                fontWeight: FontWeight.w600,
                                height: 0.04,
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 13.64),
                      Container(
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 32.74,
                              height: 32.74,
                              padding: const EdgeInsets.all(2.73),
                              decoration: ShapeDecoration(
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(4.09),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    width: 27.28,
                                    height: 27.28,
                                    clipBehavior: Clip.antiAlias,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(width: 2.73, color: Color(0xFFCBD2E0)),
                                        borderRadius: BorderRadius.circular(13640.83),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(width: 38),
                            Text(
                              'hindi',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFF285352),
                                fontSize: 24.56,
                                fontFamily: 'Lora',
                                fontWeight: FontWeight.w600,
                                height: 0.04,
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 13.64),
                      Container(
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 32.74,
                              height: 32.74,
                              padding: const EdgeInsets.all(2.73),
                              decoration: ShapeDecoration(
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(4.09),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    width: 27.28,
                                    height: 27.28,
                                    clipBehavior: Clip.antiAlias,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(width: 2.73, color: Color(0xFFCBD2E0)),
                                        borderRadius: BorderRadius.circular(13640.83),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(width: 38),
                            Text(
                              'Punjabi',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFF285352),
                                fontSize: 24.56,
                                fontFamily: 'Lora',
                                fontWeight: FontWeight.w600,
                                height: 0.04,
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 13.64),
                      Container(
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 32.74,
                              height: 32.74,
                              padding: const EdgeInsets.all(2.73),
                              decoration: ShapeDecoration(
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(4.09),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    width: 27.28,
                                    height: 27.28,
                                    clipBehavior: Clip.antiAlias,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(width: 2.73, color: Color(0xFFCBD2E0)),
                                        borderRadius: BorderRadius.circular(13640.83),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(width: 38),
                            Text(
                              'marathi',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFF285352),
                                fontSize: 24.56,
                                fontFamily: 'Lora',
                                fontWeight: FontWeight.w600,
                                height: 0.04,
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 13.64),
                      Container(
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 32.74,
                              height: 32.74,
                              padding: const EdgeInsets.all(2.73),
                              decoration: ShapeDecoration(
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(4.09),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    width: 27.28,
                                    height: 27.28,
                                    clipBehavior: Clip.antiAlias,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(width: 2.73, color: Color(0xFFCBD2E0)),
                                        borderRadius: BorderRadius.circular(13640.83),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(width: 38),
                            Text(
                              'gujrati',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFF285352),
                                fontSize: 24.56,
                                fontFamily: 'Lora',
                                fontWeight: FontWeight.w600,
                                height: 0.04,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}